site_name: OptiPFair
site_description: A library for structured pruning & Biasd visualization of large language models
site_author: Pere Martra
site_url: https://peremartra.github.io/optipfair/

repo_name: peremartra/optipfair
repo_url: https://github.com/peremartra/optipfair
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Usage: usage.md
  - Examples: examples.md
  - API Reference: api.md
  - Contributing: contributing.md
  - Roadmap: roadmap.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [optipfair]
          options:
            docstring_style: google
            show_source: true
            show_category_heading: true
            show_submodules: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/peremartra
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/optipfair/

copyright: Copyright &copy; 2025 OptiPFair Contributors