name: Deploy Documentation
on:
  push:
    branches: [main]
    paths: 
      - 'docs/**'
      - 'mkdocs.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install mkdocs mkdocs-material mkdocstrings[python]
    - run: mkdocs gh-deploy --force